[firebase]
# type = "service_account"
# project_id = "genx-2e398"
# private_key_id = "bf1553a2d04ee4a527d4a6b4e07bad62dbb47565"
# private_key = """-----BEGIN PRIVATE KEY-----
# MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC63FaEysCQ6AtS
# CTI04n3ZL7RJsCmBdgcVeuXoDia3HoDiVgyWp8ZwxqtEv/NRfpvgM+y81bkVD9Of
# +O1EO1SSJ8t8n3FNBh4z9TaEQ/XqZhzZuLHEKRd8pNmWFuGB+RCjhHl9mWhLub0v
# XPkuyvvhiZMwImifY83LoAsuO/SQFjt/+9eu+d1VM2tfm69AFw7EzQ5AxNX7AOo0
# 6UrD3YDJuqu7JHkdC7lJvVnRuP96MZTGrzafyO8eBCCGVXLWrFCSaIRavsEqHBtP
# gP/+Ji49Q64XWl8VoEnkQmiFUfpAgwbe7Dysanu/pQ7X2mFhg7iKzXDyW5FJIadR
# VohnbAMHAgMBAAECggEAODr8+CnxR8nkOjQVPS/ZEiXWWYRfARvM5uxcSfgUM2/E
# 9hdR43Yqc559RIuEw4XXj2DgwTSJZSqlktK8R5eZDABYrjBmznhkV1tXo/a1hmtj
# DCuVpwN8k2AiMBXDl7KlDKfdTWwAJCWJJjsSqz+fC5A0UDxSgoBsmfWX17poDoF2
# kc58aJF5HpWcpqIy3C0Mn6iLCUi8czJ3MCM2ISUoiYiz3d79pHmRuFHsJyU+iRdv
# WbhvK0TokhekB38AdfmnkEn+E1N/P5xeKO1PbG0yr2bLPB7wzu8qvmTitOcqcM8Z
# cAcFSyGylQsAl5QR4+8zjSrF0O6GauF09HhFvPdVJQKBgQDdrsEZ5TTR/G2WARrM
# SuElK8ZIlPZEKkD5Q4M/YsbkszRtZlrtbeSiLYWQP2BewzH/uTvaLKgmeHCTRxqL
# +c7Jk36BD77BrSVybuijbUeB1v8PLTksntv4csby3PGYC6R6zJmICQA1pBGB6NbS
# rlT3y98D9obqEgmQovilA+dfjQKBgQDXyZiW5akP1l13EuEojkmPvFuf9TCpgZTL
# bV9lFAE9s9DLEvhfoMEZEl7DMNRgozCrcuXl9W8z3inKGVhoWkOyx9Rc2yZ90MJg
# TE9Tya9dFfTVMC8+Q9tOA/znA9Izb+sTrg3CuhsJWsqjnCfWy4U2IENq3X1+7+jE
# 9jMF6HCt4wKBgGWVv0dukVXopw8mUnFrnuC5vpNkL7Xs5vlSxsI1MY97z3qSfPhw
# c2UeFyaS5EaIjFDzQUopTKTUbEIRQ0kBoJEe1cmuvWtjPNXDnTfGzA3jx93ci2a3
# JXYkoqaIOO3D6Aud1n1QIphyJtOxL0A8QxOKiRf30LtSqK9u/yIfN9fBAoGAIPIg
# n/lUhJyADKwPQHfo908U1ilDUr38D8sVI4OYZOlNWZP94+vRT5ikazzLUC3aQnL6
# cs+0OMEUtEyGWPhfGa6017CGAfObmcRM4EgMxDOT+/CtZd5KX3Dwbf0BXOUbiRer
# 9i0f75+zDKPM2VidcBQg9vH2NSk/6sKEK8S/X20CgYB5MdWMPBrOtjQoddcSxCZk
# SnhH5iuUYgEwIaBKQTuDk55DlQnLnQo6MQw4WXrEzqvv8lQ7qt9OlWzwteTwYRya
# 6NrMnVaH3pVqm72sUkfxXKFPtmgkqnhTQkEELNR3QXBib4++sTL8F6pSLc4gOcvC
# 6T2mYMil6jIJq799SS4snA==
# -----END PRIVATE KEY-----
# """
# client_email = "firebase-adminsdk-fbsvc@genx-2e398.iam.gserviceaccount.com"
# client_id = "114037112628905113816"
# auth_uri = "https://accounts.google.com/o/oauth2/auth"
# token_uri = "https://oauth2.googleapis.com/token"
# auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
# client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40genx-2e398.iam.gserviceaccount.com"
# universe_domain = "googleapis.com"
type = "service_account"
project_id = "genx-2e398"
private_key_id = "bf1553a2d04ee4a527d4a6b4e07bad62dbb47565"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmqv+BiaoxlwRW
l4zy3JF4/RjCj0+4p5FF4MaW6JgmwK1f9aeodpFvftEcDKxezwIOcW2dCa0s6I8T
ibQPP/28HOzDI59cVEOj5qvCvgWCvBwZ0sdsvW+ONaGRsAQsbKnwT3mgOBuVSIvx
hHm6rKUzXPE5ZRl61Y/i+xEtDrMNEg104S4t1FRlM8nJj6lMKAY9jX7jgOL83wrT
66PhiZRe8ewccve+HCfEtdt6Ivfq/F48vSl2OjdN+XQpHEhNNyDGDH4C79RQntXg
vqwR44T0NvxmqqJ1xoJovSyOqHbp+KGvzwXG6l+QqZFbllCwJ56J+1c9UvDCO5VH
qDjIkIYpAgMBAAECggEABNt68tWGRke2cqecDf/rpXEK5bCzjBgmHbk9UGya8pYu
91r7deduuacihQTBiUnTL4SSwz7i8yob8V/UBZXB2VemdtF09YXnKsGwQ86x7mt5
Di+cbEjhFW3utYZBuOG52i0WyFqaQzGIEpPf0FbzwZl11kxh/7h1pxHWIFALW9gc
vCQMBBahGnp1Pdr127JfH085hh62zjfDj4N+4triebNfclgaQeIaXCvxPdPUq9TL
IefcBMCio+eYzrFRCw1heozokF5Euj/m7yCeggGWG9c+7fiv/7Ci8P4XiuwrMUQ5
b4jZBElYl1JwOv16INbm998ot5FjWeTgzN+gloWuYQKBgQDmCtcQGg6Z2WDlH1yX
7ACGtFHezqE7qPOV29Fq3erIjn1SjFyy4WEZPmCZq84ODeqV9m3UjyHXW4TRV9fa
YaHp5F4FUdddBP/1KF3IlfL+d0gbYuNwKBReTcJpWYoSKge4BwdDJmVfnr4vP5cr
NGvpnINcf9z3gO+yhFSysAV9TQKBgQC5eXt8r24uM2v+n/xr5IvpdrCoNhTfw6Ap
NEZmRQ7vp/+SGFLFRCeW7pGmXELi8HEVYg4z2VYcUqiLdQl9r79/RIt5Uyl5o3X5
PnhCS2hVgmGBsHY+2hNc/AOJcCGYSyTSo2GN70gIKle9mGrB/VZnny1hCuq50gUG
LjncqP4uTQKBgCjGAxh3hd7/CI2T4XWL/wvhKiGzviA08fe93oBylQq3Nr9K4aNT
D0LKK5URPpR/IvUxmIX0WKszLXdtenTamTg7oe6PcvypxjRN01GaQleYDM/N10Ip
2HJelfbWSAKwMG4N0Nu2EoHAQTVesAyYXggqFZ5vi1rTH6kki16glFiBAoGBAJBw
P6+I+tf16atAMhZfxGmKqeZFP5pGwUp1UEHCk/Akt42xbXv8KIyMu1Z/0QLkVlxd
oUvVfA7QfDsmaL69h/b3jVptXgZBOtVgRczy5ox43bBemKc3sw6dn69/aFouYr26
yHT9G+5n8y5OLQ1nWcuWlYNWOhd9q7X1d9AUtuWdAoGAOZocXCSblOKZhC6mola7
WT5478Y0knaTlLmQ6ElxzJh1lpDJBXrHHuvXHX8CqC+yFoEfq0Hlm3Twb7RPbHGK
AymA2fWhymW9FEwG+487CabtxmH5xQ/XoFo2Z5C9pUvcIsOAFf51DoQQpdKCGM8r
164+fxWFZCZsoMAKrZcj3bI=
-----END PRIVATE KEY-----"""
client_email = "legal-document-analyzer@genx-2e398.iam.gserviceaccount.com"
client_id = "107521140093964086584"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/legal-document-analyzer%40genx-2e398.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


[google_cloud]
project_id = "genx-2e398"
location = "us-central1"
